### **Extraer los datos de fechas, partidos y goles de todos los equipos `de la liga de cualquier pais`, visualizarlos en un Dataframe y exportarlos a un archivo CSV**

#### **`Prueba 1`**

Reutilizando el código utilizado en el archivo **`1-adamchoi.ipynb`** vamos a inspeccionar el **`Dropdown`** de "**`Select Country`**":

<center><img src="https://i.postimg.cc/zBjL0ky4/ws-297.png"></center>

<center><img src="https://i.postimg.cc/Kjp1yvrN/ws-298.png"></center>

Por lo tanto, para generar una seleccion en un **`Dropdown`** hacemos lo siguiente:

In [4]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
import pandas as pd
import time

website = 'https://www.adamchoi.co.uk/overs/detailed'
# Se recomienda utilizar Chrome, pero podriamos utilizar Firefox, Safari, Edge, etc.
driver = webdriver.Chrome()
driver.get(website)

all_matches_button = driver.find_element(by=By.XPATH, value='//label[@analytics-event="All matches"]')
all_matches_button.click()

############################################################################################
# seleccionar dropdown y seleccionar elemento dentro por texto visible
# Tambien podriamos usar --> dropdown = Select(driver.find_element(by=By.ID, value='country'))
elemento = driver.find_element(by=By.XPATH, value='//select[@id="country"]')
dropdown = Select(elemento)
dropdown.select_by_visible_text('Spain')
# implicit wait (útil en sitios web controlados por JavaScript cuando los elementos necesitan segundos para cargarse y evitar el error "ElementNotVisibleException")
time.sleep(3)
############################################################################################

partidos = driver.find_elements(by=By.XPATH, value='//tr[@data-ng-repeat="match in ::dtc.$scope.matches"]')

fecha = []
equipo_local = []
resultado = []
equipo_visita = []

# Así que como vemos aquí, ya no estamos usando "driver.find_element(by=By.XPATH)", porque queremos usar el contexto "partido". 
# Así que queremos tener "partidos" como referencia para nuestro XPath. Así que si queremos usar ese contexto "partido", tenemos que 
# escribir "partido" en lugar de driver. Y luego en el XPath, tenemos que escribir el signo de "punto", porque ese signo de punto 
# especifica que queremos usar el contexto actual y luego tenemos que construir ese XPath.

for partido in partidos:
    fecha.append(partido.find_element(by=By.XPATH, value='./td[1]').text)
    equipo_local.append(partido.find_element(by=By.XPATH, value='./td[2]').text)
    resultado.append(partido.find_element(by=By.XPATH, value='./td[3]').text)
    equipo_visita.append(partido.find_element(by=By.XPATH, value='./td[4]').text)

driver.quit() # Nos sirve para cerrar la ventana que se nos abre
    
# Crear Dataframe en Pandas y exportar a CSV (Excel)
df = pd.DataFrame({'fecha': fecha, 'equipo_local': equipo_local, 'resultado': resultado, 'equipo_visita': equipo_visita})
df.to_csv('football_data2.csv', index=False)
df

          fecha equipo_local resultado equipo_visita
0    14-08-2023        Cadiz     1 - 0        Alaves
1    21-08-2023       Alaves     4 - 3       Sevilla
2    28-08-2023       Getafe     1 - 0        Alaves
3    02-09-2023       Alaves     1 - 0      Valencia
4    15-09-2023    Vallecano     2 - 0        Alaves
..          ...          ...       ...           ...
611  03-03-2024   Villarreal     5 - 1       Granada
612  10-03-2024        Betis     2 - 3    Villarreal
613  17-03-2024   Villarreal     1 - 0      Valencia
614  01-04-2024   Villarreal     1 - 2    Ath Madrid
615  14-04-2024   Ath Bilbao     ? - ?    Villarreal

[616 rows x 4 columns]

#### **`Prueba 2`**

Reutilizando el código utilizado en el archivo **`1-adamchoi.ipynb`** vamos a inspeccionar el **`Dropdown`** de "**`Select Country`**" y "**`Select League`**":

<center><img src="https://i.postimg.cc/ht6jStzy/ws-300.png"></center>

<center><img src="https://i.postimg.cc/Kjp1yvrN/ws-298.png"></center>

<center><img src="https://i.postimg.cc/pLhW1MGD/ws-299.png"></center>

Por lo tanto, para generar una seleccion en ambos **`Dropdown`** hacemos lo siguiente:

In [5]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
import pandas as pd
import time

website = 'https://www.adamchoi.co.uk/overs/detailed'
# Se recomienda utilizar Chrome, pero podriamos utilizar Firefox, Safari, Edge, etc.
driver = webdriver.Chrome()
driver.get(website)

all_matches_button = driver.find_element(by=By.XPATH, value='//label[@analytics-event="All matches"]')
all_matches_button.click()

############################################################################################
# seleccionar dropdown y seleccionar elemento dentro por texto visible
# Tambien podriamos usar --> dropdown = Select(driver.find_element(by=By.ID, value='country'))
elemento = driver.find_element(by=By.XPATH, value='//select[@id="country"]')
dropdown = Select(elemento)
dropdown.select_by_visible_text('Spain')

element = driver.find_element(by=By.ID, value='league')
desplegable = Select(element)
desplegable.select_by_visible_text('Segunda Division')

# implicit wait (útil en sitios web controlados por JavaScript cuando los elementos necesitan segundos para cargarse y evitar el error "ElementNotVisibleException")
time.sleep(6)
############################################################################################

partidos = driver.find_elements(by=By.XPATH, value='//tr[@data-ng-repeat="match in ::dtc.$scope.matches"]')

fecha = []
equipo_local = []
resultado = []
equipo_visita = []

# Así que como vemos aquí, ya no estamos usando "driver.find_element(by=By.XPATH)", porque queremos usar el contexto "partido". 
# Así que queremos tener "partidos" como referencia para nuestro XPath. Así que si queremos usar ese contexto "partido", tenemos que 
# escribir "partido" en lugar de driver. Y luego en el XPath, tenemos que escribir el signo de "punto", porque ese signo de punto 
# especifica que queremos usar el contexto actual y luego tenemos que construir ese XPath.

for partido in partidos:
    fecha.append(partido.find_element(by=By.XPATH, value='./td[1]').text)
    equipo_local.append(partido.find_element(by=By.XPATH, value='./td[2]').text)
    resultado.append(partido.find_element(by=By.XPATH, value='./td[3]').text)
    equipo_visita.append(partido.find_element(by=By.XPATH, value='./td[4]').text)

driver.quit() # Nos sirve para cerrar la ventana que se nos abre
    
# Crear Dataframe en Pandas y exportar a CSV (Excel)
df = pd.DataFrame({'fecha': fecha, 'equipo_local': equipo_local, 'resultado': resultado, 'equipo_visita': equipo_visita})
df.to_csv('football_data3.csv', index=False)
df

          fecha equipo_local resultado equipo_visita
0    13-08-2023     Albacete     1 - 1       Espanol
1    20-08-2023     Albacete     2 - 2    Amorebieta
2    27-08-2023      Leganes     2 - 0      Albacete
3    01-09-2023     Albacete     2 - 0    Valladolid
4    09-09-2023     Tenerife     2 - 0      Albacete
..          ...          ...       ...           ...
743  09-03-2024   Valladolid     2 - 0      Zaragoza
744  17-03-2024     Zaragoza     0 - 1       Espanol
745  24-03-2024     Mirandes     0 - 0      Zaragoza
746  31-03-2024     Zaragoza     3 - 1      Tenerife
747  06-04-2024      Levante     ? - ?      Zaragoza

[748 rows x 4 columns]