### **Data Cleaning con Pandas**

#### **1 - Cargamos las librerias que vamos a utilizar**

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

#### **2 - Importamos el archivo CSV**

In [104]:
df_netflix = pd.read_csv('netflix_titles.csv')

df_netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [99]:
df_netflix.shape

(8807, 12)

#### **3 - Importar el modulo de **`calidad_datos`** para analizar datos estadisticos, nulos y ceros del Dataframe**

In [3]:
from calidad_datos import calidad_datos

d = calidad_datos(df_netflix)
d = np.round(d, 2)
d

,tipo,nulos,porc_nulos,ceros,porc_ceros,count,unique,top,freq,mean,std,min,25%,50%,75%,max,limit_inf,limit_sup,outliers
release_year,int64,0,0.00,0,0.0,8807.0,NaN,NaN,NaN,2014.180198,8.819312,1925.0,2013.0,2017.0,2019.0,2021.0,2000.951229,2027.409166,562
show_id,object,0,0.00,0,0.0,8807,8807,s1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
type,object,0,0.00,0,0.0,8807,2,Movie,6131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
title,object,0,0.00,0,0.0,8807,8807,Dick Johnson Is Dead,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
director,object,2634,29.91,0,0.0,6173,4528,Rajiv Chilaka,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
cast,object,825,9.37,0,0.0,7982,7692,David Attenborough,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
country,object,831,9.44,0,0.0,7976,748,United States,2818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
date_added,object,10,0.11,0,0.0,8797,1767,"January 1, 2020",109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
rating,object,4,0.05,0,0.0,8803,17,TV-MA,3207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
duration,object,3,0.03,0,0.0,8804,220,1 Season,1793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
listed_in,object,0,0.00,0,0.0,8807,514,"Dramas, International Movies",362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
description,object,0,0.00,0,0.0,8807,8775,"Paranormal activity at a lush, abandoned prope...",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

#### **4 - Filtrar los datos vacios**

In [ ]:
df_netflix.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

Visualizamos los `indices` que poseen valores `NaN` en la columna `director`

In [ ]:
no_director = df_netflix[df_netflix['director'].isnull()].index
no_director

Index([   1,    3,    4,   10,   14,   15,   17,   19,   21,   25,
       ...
       8775, 8780, 8783, 8784, 8785, 8795, 8796, 8797, 8800, 8803],
      dtype='int64', length=2634)

##### `Forma 1`

Filtramos todos los datos que no tengan director, dejando solo asi aquellas series y peliculas que si tengan este dato:

In [ ]:
df_netflix = df_netflix[df_netflix['director'].str.len() > 0]

##### `Forma 2`

Filtramos todos los datos que no tengan director, dejando solo asi aquellas series y peliculas que si tengan este dato:

In [ ]:
# Lo mismo ---> df_netflix[~df_netflix['director'].isnull()]
df_netflix  = df_netflix[~df_netflix.director.isnull()]

##### `Forma 3` - Utilizando RegEx

`na=True` significa que devolverá los valroes NaN de la columna seleccionada

In [ ]:
#df_netflix[~df_netflix['director'].str.contains(r'^(?:\s+)?$', na=True, regex=True)]
#df_netflix[~df_netflix['director'].str.contains(r'^(?:\s+)', na=True, regex=True)]
df_netflix = df_netflix[~df_netflix['director'].str.contains(r'(?:\s+)', na=True, regex=True)]

##### `Forma 4` - Utilizando dropna()

In [105]:
# dropear valores null solo de la columna "director"
df_netflix = df_netflix.dropna(subset=['director'])
df_netflix.shape

(6173, 12)

In [ ]:
# dropear valores null de todas las columnas
df_netflix.dropna(axis=0, how="any", inplace=True)

#### **5 - Filtrar datos mal ingresados**

Revisemos las columnas de nuestro dataframe (dar por entendido que realizamos el paso de eliminar solo las filas que posean datos `NaN` en la columna `director`):

In [106]:
df_netflix.shape

(6173, 12)

In [107]:
df_netflix.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [108]:
df_netflix.columns.values

array(['show_id', 'type', 'title', 'director', 'cast', 'country',
       'date_added', 'release_year', 'rating', 'duration', 'listed_in',
       'description'], dtype=object)

In [109]:
df_netflix.shape

(6173, 12)

In [110]:
df_netflix.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

Revisamos los datos de cada columna:

##### Columna **`show_id`**

In [111]:
df_netflix['show_id'].unique()

array(['s1', 's3', 's6', ..., 's8805', 's8806', 's8807'], dtype=object)

In [112]:
df_showid = df_netflix[df_netflix['show_id'].str.contains(r'(^s)', na=False, regex=True)]
df_showid.shape

C:\Users\Alfonso\AppData\Local\Temp\ipykernel_19948\3445534726.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_showid = df_netflix[df_netflix['show_id'].str.contains(r'(^s)', na=False, regex=True)]

(6173, 12)

##### Columna **`type`**

In [113]:
df_netflix['type'].unique()

array(['Movie', 'TV Show'], dtype=object)

##### Columna **`country`**

In [114]:
df_netflix['country'].unique()

array(['United States', nan,
       'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia',
       'United Kingdom', 'Germany, Czech Republic', 'India',
       'United States, India, France', 'China, Canada, United States',
       'South Africa, United States, Japan', 'Japan', 'Nigeria',
       'Spain, United States', 'France', 'United Kingdom, United States',
       'United Kingdom, Australia, France',
       'United Kingdom, Australia, France, United States',
       'United States, Canada', 'Germany, United States',
       'South Africa, United States', 'United States, Mexico',
       'United States, Italy, France, Japan',
       'United States, Italy, Romania, United Kingdom',
       'Australia, United States', 'Argentina, Venezuela',
       'United States, United Kingdom, Canada', 'China, Hong Kong',
       'Canada', 'Hong Kong', 'United States, China, Hong Kong',
       'Italy, United States', 'United States, Germany',
       'United Kingdom, Canada, United States',
       'United States, United Kingdom', 'India, Nepal',
       'New Zealand, Australia, France, United States',
       'Italy, Brazil, Greece', 'Spain', 'Colombia',
       'United States, Japan', 'Mexico', 'Belgium, United Kingdom',
       'Switzerland, United Kingdom, Australia', 'South Africa',
       'Canada, United States', 'Brazil', 'Argentina', 'Argentina, Spain',
       'United States, Nigeria', 'Taiwan', 'Bulgaria, United States',
       'Spain, United Kingdom, United States', 'United States, China',
       'United States, France',
       'Spain, France, United Kingdom, United States',
       ', France, Algeria', 'Poland',
       'France, Israel, Germany, United States, United Kingdom',
       'Australia', 'New Zealand', 'Saudi Arabia', 'Thailand',
       'Indonesia', 'Egypt, Denmark, Germany', 'Italy',
       'United States, Switzerland', 'Hong Kong, Canada, United States',
       'Kuwait, United States', 'France, Canada, United States, Spain',
       'France, Netherlands, Singapore', 'Egypt', 'Malaysia',
       'South Korea, Czech Republic', 'South Korea', 'Vietnam',
       'United Kingdom, Belgium',
       'United Kingdom, Australia, United States',
       'France, Japan, United States',
       'United Kingdom, Germany, Spain, United States',
       'United Kingdom, United States, France, Italy',
       'United States, Germany, Canada',
       'United States, France, Italy, United Kingdom',
       'United States, United Kingdom, Germany, Hungary',
       'United States, New Zealand', 'Lebanon', 'Romania',
       'Lebanon, Syria', 'Philippines', 'Germany', 'United States, India',
       'Philippines, Singapore, Indonesia',
       'China, United States, Canada', 'Lebanon, United Arab Emirates',
       'Canada, United States, Denmark', 'United Arab Emirates',
       'Mexico, France, Colombia', 'Sweden',
       'Germany, United States, France', 'United States, Bulgaria',
       'United Kingdom, France, Germany, United States',
       'Syria, France, Lebanon, Qatar', 'Belgium, Netherlands',
       'Mauritius', 'Canada, South Africa', 'Austria', 'Mexico, Brazil',
       'France, United States', 'China', 'Turkey', 'Germany, France',
       'United Kingdom, France, Spain, United States',
       'United States, Australia',
       'United States, United Kingdom, France', 'United States, Russia',
       'United States, United Kingdom, New Zealand',
       'Canada, Nigeria, United States',
       'France, United States, United Kingdom, Canada',
       'India, United Kingdom', 'Canada, United States, Mexico',
       'United Kingdom, Germany, United States',
       'Czech Republic, United Kingdom, United States', 'China, Taiwan',
       'United States, Brazil, Japan, Spain, India',
       'United States, China, United Kingdom', 'Cameroon', 'Netherlands',
       'Lebanon, Palestine, Denmark, Qatar', 'Japan, United States',
       'Egypt, Saudi Arabia',
       'United Kingdom, France, Poland, Germany, United States',
       'Ireland, Switzerland, United Kingdom, France, United States',
       'China, United Kingdom', 'United Kingdom, South Africa, France',
       'Ireland, United Kingdom, France, Germany',
       'Russia, United States', 'United Kingdom, United States, France',
       'United Kingdom,', 'Belgium',
       'United States, India, United Kingdom', 'Kenya',
       'Spain, Argentina', 'India, United Kingdom, France, Qatar',
       'Belgium, France', 'Argentina, Chile', 'United States, Thailand',
       'Chile, Brazil', 'Canada, United States, United Kingdom',
       'Uruguay', 'United States, Cambodia, Romania', 'Bangladesh',
       'Spain, Belgium, United States',
       'United Kingdom, United States, Australia',
       'Portugal, United States', 'Portugal, Spain',
       'India, United States', 'United Kingdom, Ireland',
       'United Kingdom, Spain, United States', 'Hungary, United States',
       'United States, South Korea',
       'Canada, United States, Cayman Islands', 'India, France',
       'France, Canada', 'Canada, Hungary, United States', 'Norway',
       'Canada, United Kingdom, United States',
       'United Kingdom, Germany, France, United States',
       'France, Algeria',
       'Philippines, Canada, United Kingdom, United States',
       'Ireland, France, Iceland, United States, Mexico, Belgium, United Kingdom, Hong Kong',
       'Singapore', 'France, Belgium', 'Iceland',
       'United States, France, Serbia', 'United States, Italy',
       'Hong Kong, United States',
       'United States, Malta, France, United Kingdom',
       'United States, China, Canada', 'Spain, France, Canada',
       'United States, China, Colombia', 'Spain, Thailand, United States',
       'Mexico, Spain', 'Ireland, Luxembourg, Belgium',
       'China, United States', 'Canada, Belgium',
       'Canada, United Kingdom',
       'Lebanon, United Arab Emirates, France, Switzerland, Germany',
       'France, Belgium, Italy',
       'Lebanon, United States, United Arab Emirates', 'Lebanon, France',
       'France, Lebanon', 'France, Lebanon, United Kingdom',
       'France, Norway, Lebanon, Belgium', 'Lebanon, Canada, France',
       'Sweden, Czech Republic, United Kingdom, Denmark, Netherlands',
       'United States, United Kingdom, India', 'Indonesia, Netherlands',
       'Turkey, South Korea', 'Russia', 'Serbia, United States',
       'Namibia', 'United Kingdom, Kenya',
       'United Kingdom, France, United States, Belgium, Luxembourg, China, Germany',
       'Thailand, United States',
       'United States, France, Canada, Belgium',
       'Germany, China, United Kingdom',
       'Hong Kong, Iceland, United States',
       'United States, Belgium, Canada, France', 'South Africa, Angola',
       'United States, Philippines',
       'United States, United Kingdom, Canada, China',
       'United States, Canada, United Kingdom', 'Turkey, United States',
       'Peru, Germany, Norway', 'Mozambique', 'Brazil, France',
       'China, Spain, South Korea, United States', 'Spain, Germany',
       'Hong Kong, China', 'France, Belgium, Luxembourg, Cambodia,',
       'Indonesia, United Kingdom',
       'Switzerland, France, Belgium, United States', 'Ghana',
       'Spain, France, Canada, United States', 'United Kingdom, Nigeria',
       'Chile', 'France, Egypt', 'Egypt, France',
       'France, Brazil, Spain, Belgium', 'Egypt, Algeria',
       'Canada, South Korea, United States', 'Nigeria, United Kingdom',
       'United Arab Emirates, Jordan, Lebanon, Saudi Arabia',
       'Saudi Arabia, United Arab Emirates', 'Zimbabwe',
       'United Kingdom, Germany, United Arab Emirates, New Zealand',
       'Romania, United States', 'Mexico, United States', 'Kuwait',
       'Canada, Nigeria',
       'Saudi Arabia, Netherlands, Germany, Jordan, United Arab Emirates, United States',
       'United Kingdom, Germany, United States, France',
       'India, United Kingdom, China, Canada, Japan, South Korea, United States',
       'Turkey, India', 'Italy, Turkey',
       'United Kingdom, United States, Japan',
       'France, Belgium, United States', 'Uruguay, Argentina',
       'United States, United Kingdom, Japan', 'United Kingdom, Italy',
       'Ireland, United Kingdom',
       'United Kingdom, France, Belgium, Canada, United States',
       'Netherlands, Germany, Denmark, United Kingdom', 'Hungary',
       'South Korea, United States', 'Pakistan, United States',
       'Romania, France, Switzerland, Germany', 'Romania, United Kingdom',
       'France, Malta, United States',
       'United Kingdom, France, Belgium, Ireland, United States',
       'United States, Norway, Canada', 'Poland, United States',
       'Kenya, United States',
       'France, South Korea, Japan, United States', 'Taiwan, Malaysia',
       'Uruguay, Argentina, Germany, Spain',
       'United States, United Kingdom, France, Germany, Japan',
       'United States, France, Japan',
       'United Kingdom, France, United States',
       'Spain, France, United States',
       'Indonesia, South Korea, Singapore', 'United States, Spain',
       'Spain, Germany, Denmark, United States',
       'Argentina, Uruguay, Serbia', 'Israel, United States',
       'France, Japan',
       'United Kingdom, United States, Germany, Denmark, Belgium, Japan',
       'India, Germany', 'India, United Kingdom, Canada, United States',
       'Philippines, United States', 'Romania, Bulgaria, Hungary',
       'Uruguay, Guatemala', 'France, Senegal, Belgium', 'Canada, Norway',
       'Finland, Germany, Belgium', 'United Kingdom, France',
       'United States, Chile', 'United Kingdom, Japan, United States',
       'Spain, United Kingdom', 'United States, South Korea, Japan',
       'United Kingdom, Hungary, Australia', 'Italy, Belgium',
       'United States, United Kingdom, Germany', 'Switzerland',
       'Singapore, Malaysia',
       'France, Belgium, Luxembourg, Romania, Canada, United States',
       'South Africa, Nigeria', 'Spain, France', 'Pakistan',
       'Brazil, United States',
       'Denmark, Brazil, France, Portugal, Sweden', 'India, Turkey',
       'Philippines, Singapore', 'Taiwan, China, France, United States',
       'Germany, Italy', 'Colombia, Peru, United Kingdom',
       'Thailand, China, United States', 'Argentina, United States',
       'Sweden, United States', 'Uruguay, Spain, Mexico',
       'France, Luxembourg, Canada', 'Denmark, Spain', 'Chile, Argentina',
       'United Kingdom, Belgium, Sweden', 'Denmark', 'Italy, France',
       'Canada, Germany', 'Pakistan, United Arab Emirates',
       'Ghana, United States', 'Mexico, Finland',
       'United Arab Emirates, United Kingdom, India',
       'Netherlands, Belgium', 'United States, Taiwan',
       'Austria, Iraq, United States', 'United Kingdom, Malawi',
       'Paraguay, Argentina', 'United Kingdom, Russia, United States',
       'India, Pakistan', 'Indonesia, Singapore', 'Spain, Belgium',
       'Iceland, Sweden, Belgium', 'Uruguay, Argentina, Spain',
       'United Kingdom, Ireland, United States',
       'Canada, Germany, France, United States', 'United Kingdom, Japan',
       'Norway, Denmark, Netherlands, Sweden',
       'Hong Kong, China, United States', 'Ireland, Canada',
       'Italy, Switzerland, France, Germany', 'Mexico, Netherlands',
       'France, Iran, United States', 'United Kingdom, India',
       'Russia, Poland, Serbia', 'Spain, Portugal', 'Peru',
       'Mexico, Argentina',
       'United Kingdom, Canada, United States, Cayman Islands',
       'Indonesia, United States',
       'United States, Israel, United Kingdom, Canada',
       'Norway, Iceland, United States',
       'United Kingdom, India, United States', 'India, Australia',
       'United States,', 'Belgium, United Kingdom, United States',
       'India, Germany, Austria', 'Spain, Mexico', 'China, Japan',
       'Argentina, France', 'China, United States, United Kingdom',
       'France, Luxembourg, United States',
       'China, United States, Australia', 'Colombia, Mexico',
       'United States, Canada, Ireland', 'Israel', 'Chile, Peru',
       'Argentina, Italy', 'Canada, Japan, United States',
       'United Kingdom, Canada, United States, Germany',
       'Italy, Switzerland, Albania, Poland', 'Cambodia',
       'Italy, United States, Argentina',
       'United States, Canada, Indonesia, United Kingdom, China, Singapore',
       'Spain, Colombia', 'Bulgaria',
       'Argentina, Brazil, France, Poland, Germany, Denmark',
       'United Kingdom, Spain, United States, Germany',
       'Philippines, Qatar', 'Netherlands, Belgium, Germany, Jordan',
       'United Arab Emirates, United States', 'United Kingdom, Germany',
       'United Kingdom, Canada', 'Georgia', 'Soviet Union, India',
       'Australia, United Arab Emirates', 'Czech Republic, United States',
       'South Korea, China, United States', 'India, Soviet Union',
       'India, Mexico', 'Georgia, Germany, France',
       'United Arab Emirates, Romania', 'Australia, Canada',
       'India, Malaysia', 'Germany, Jordan, Netherlands',
       'Turkey, France, Germany, Poland', 'Greece, United States',
       'Norway, Germany', 'France, Morocco', 'Cambodia, United States',
       'United States, Denmark',
       'United Kingdom, Italy, Israel, Peru, United States',
       'Argentina, Uruguay, Spain, France',
       'United Kingdom, France, United States, Belgium',
       'France, Canada, China, Cambodia',
       'United Kingdom, France, Belgium, United States', 'Ireland',
       'Chile, France', 'Netherlands, United States',
       'France, United Kingdom, India', 'Czech Republic, Slovakia',
       'Singapore, France', 'Spain, Switzerland',
       'United States, Australia, China',
       'South Africa, United States, Germany', 'Spain, Italy, Argentina',
       'Chile, Spain, Argentina, Germany', 'West Germany',
       'Austria, Czech Republic', 'Lebanon, Qatar',
       'United Kingdom, Jordan, Qatar, Iran',
       'France, South Korea, Japan', 'Israel, Germany, France',
       'United States, Hungary', 'France, Qatar',
       'United Kingdom, Germany, Canada', 'Ireland, South Africa',
       'Chile, United States, France', 'Denmark, United States',
       'Belgium, France, Netherlands',
       'United Kingdom, Ukraine, United States',
       'United States, Bermuda, Ecuador',
       'United Kingdom, Egypt, United States',
       'United States, France, United Kingdom', 'Spain, Mexico, France',
       'United States, South Africa', 'Hong Kong, China, Singapore',
       'South Africa, China, United States', 'Denmark, France, Poland',
       'New Zealand, United Kingdom',
       'Netherlands, Denmark, South Africa', 'Iran, France',
       'United Kingdom, United States, France, Germany',
       'Australia, France', 'Ireland, United Kingdom, United States',
       'Spain, Italy', 'United Kingdom, France, Germany',
       'Canada, Luxembourg',
       'Brazil, Netherlands, United States, Colombia, Austria, Germany',
       'France, Canada, Belgium',
       'Bulgaria, United States, Spain, Canada', 'Sweden, Netherlands',
       'France, United States, Mexico',
       'Australia, United Kingdom, United Arab Emirates, Canada',
       'Singapore, United States',
       'Australia, Armenia, Japan, Jordan, Mexico, Mongolia, New Zealand, Philippines, South Africa, Sweden, United States, Uruguay',
       'India, Iran', 'France, Belgium, Spain',
       'Denmark, Sweden, Israel, United States', 'United States, Iceland',
       'United Kingdom, Russia',
       'United States, Israel, Italy, South Africa',
       'Netherlands, Denmark, France, Germany', 'South Korea, Japan',
       'United Kingdom, Pakistan', 'France, New Zealand',
       'United Kingdom, Czech Republic, United States, Germany, Bahamas',
       'China, Germany, India, United States', 'Germany, Sri Lanka',
       'United States, Sweden', 'United States, India, Bangladesh',
       'United States, Canada, France', 'Brazil, France, Germany',
       'United States, United Kingdom, Australia',
       'Germany, United States, Hong Kong, Singapore',
       'France, Germany, Switzerland',
       'Germany, France, Luxembourg, United Kingdom, United States',
       'United Kingdom, Canada, Italy', 'Czech Republic, France',
       'Taiwan, Hong Kong, United States, China', 'Germany, Australia',
       'United Kingdom, Poland, United States', 'Denmark, Zimbabwe',
       'United Kingdom, South Africa',
       'Finland, Sweden, Norway, Latvia, Germany',
       'South Africa, United States, New Zealand, Canada',
       'United States, Italy, United Kingdom, Liechtenstein',
       'Denmark, France, Belgium, Italy, Netherlands, United States, United Kingdom',
       'United States, Australia, Mexico',
       'United Kingdom, Czech Republic, Germany, United States',
       'France, China, Japan, United States', 'Germany, Belgium',
       'Pakistan, Norway, United States',
       'United States, Canada, Belgium, United Kingdom', 'Venezuela',
       'Canada, France, Italy, Morocco, United States',
       'Canada, Spain, France', 'United States, Indonesia',
       'Spain, France, Italy',
       'United Arab Emirates, United States, United Kingdom',
       'United Kingdom, Israel, Russia', 'United States, Brazil',
       'United States, France, Mexico', 'United States, Nicaragua',
       'France, United Kingdom, United States',
       'United Kingdom, United States, Spain, Germany, Greece, Canada',
       'Italy, Canada, France',
       'United Kingdom, Denmark, Canada, Croatia',
       'United States, France, United Kingdom, Japan',
       'United States, United Kingdom, Denmark, Sweden',
       'United States, United Kingdom, Italy',
       'United States, France, Canada, Spain',
       'Russia, United States, China', 'United States, Canada, Germany',
       'Ireland, United States', 'United States, United Arab Emirates',
       'United States, Ireland',
       'Ireland, United Kingdom, Italy, United States', 'Poland,',
       'Slovenia, Croatia, Germany, Czech Republic, Qatar',
       'Canada, United Kingdom, Netherlands',
       'United States, Spain, Germany', 'India, Japan',
       'China, South Korea, United States',
       'United Kingdom, France, Belgium',
       'Canada, Ireland, United States',
       'United Kingdom, United States, Dominican Republic',
       'United States, Senegal', 'Germany, United Kingdom, United States',
       'South Africa, Germany, Netherlands, France',
       'Ireland, United States, France', 'Germany, United States, Canada',
       'United Kingdom, Germany, Canada, United States',
       'United States, France, Canada, Lebanon, Qatar',
       'Netherlands, Belgium, United Kingdom, United States',
       'France, Belgium, China, United States',
       'United States, Chile, Israel',
       'United Kingdom, Norway, Denmark, Germany, Sweden',
       'Norway, Denmark, Sweden', 'China, India, Nepal',
       'Colombia, Mexico, United States', 'United Kingdom, South Korea',
       'United States, Greece, Brazil',
       'United States, Australia, Samoa, United Kingdom',
       'Germany, United Kingdom', 'Argentina, Chile, Peru',
       'Poland, West Germany', 'Germany, United States, Sweden',
       'Canada, Spain', 'United States, Cambodia',
       'United States, Greece', 'Norway, United Kingdom, France, Ireland',
       'United Kingdom, Poland', 'Israel, Sweden, Germany, Netherlands',
       'Switzerland, France', 'Italy, India', 'United States, Botswana',
       'Chile, Argentina, France, Spain, United States',
       'United States, India, South Korea, China',
       'Denmark, Germany, Belgium, United Kingdom, France',
       'Denmark, Germany, Belgium, United Kingdom, France, Sweden',
       'France, Switzerland, Spain, United States, United Arab Emirates',
       'Brazil, India, China, United States',
       'Denmark, France, United States, Sweden', 'Australia, Iraq',
       'China, Morocco, Hong Kong', 'Canada, United States, Germany',
       'United Kingdom, Thailand', 'Venezuela, Colombia',

##### Columna **`date_added`**

In [115]:
df_netflix['date_added'].unique()

array(['September 25, 2021', 'September 24, 2021', 'September 23, 2021',
       ..., 'December 6, 2018', 'March 9, 2016', 'January 11, 2020'],
      dtype=object)

Dado que este dato mantiene un patrón **`Mes Dia, Año`**, podemos escribir un patrón que solo nos devuelva los elementos que `NO` poseen el año al final de ese string:

In [116]:
df_date_added = df_netflix[~df_netflix['date_added'].str.contains(r'.+(\d{4}$)', na=False, regex=True)]
df_date_added.shape

C:\Users\Alfonso\AppData\Local\Temp\ipykernel_19948\3745071170.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_date_added = df_netflix[~df_netflix['date_added'].str.contains(r'.+(\d{4}$)', na=False, regex=True)]

(0, 12)

##### Columna **`release_year`**

In [117]:
df_netflix['release_year'].unique()

array([2020, 2021, 1993, 1996, 1998, 1997, 2010, 2013, 2017, 1975, 1978,
       1983, 1987, 2012, 2001, 2002, 2003, 2004, 2011, 2008, 2009, 2007,
       2005, 2006, 2018, 2019, 1994, 2015, 1982, 1989, 2014, 1990, 1991,
       1999, 2016, 1986, 1984, 1980, 1961, 2000, 1995, 1985, 1992, 1976,
       1959, 1988, 1981, 1972, 1964, 1954, 1979, 1958, 1956, 1963, 1970,
       1973, 1960, 1974, 1966, 1971, 1962, 1969, 1977, 1967, 1968, 1965,
       1945, 1946, 1942, 1955, 1944, 1947, 1943], dtype=int64)

##### Columna **`rating`**

In [118]:
df_netflix['rating'].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'R', 'TV-G',
       'TV-Y7', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR',
       'TV-Y7-FV', 'UR', nan], dtype=object)

Si revisamos los elementos de la columna "`rating`" vemos que hay 3 datos mal ingresados [`'74 min'`, `'84 min'`, `'66 min'`] que corresponden a la columna "`duration`":

In [119]:
df_netflix[df_netflix['rating'].str.contains(r'(min$)', na=False, regex=True)]

C:\Users\Alfonso\AppData\Local\Temp\ipykernel_19948\551959569.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_netflix[df_netflix['rating'].str.contains(r'(min$)', na=False, regex=True)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

- Podemos crear un nuevo dataframe sin esas 3 filas.

In [123]:
df_netflix.shape

(6173, 12)

In [124]:
df_netflix = df_netflix[~df_netflix['rating'].str.contains(r'(?:min$)', na=False, regex=True)]
df_netflix.shape

(6170, 12)

##### Columna **`duration`**

In [125]:
df_netflix['duration'].unique()

array(['90 min', '1 Season', '91 min', '125 min', '9 Seasons', '104 min',
       '127 min', '67 min', '94 min', '161 min', '61 min', '166 min',
       '147 min', '103 min', '97 min', '106 min', '111 min', '110 min',
       '105 min', '96 min', '124 min', '116 min', '98 min', '23 min',
       '115 min', '122 min', '99 min', '88 min', '100 min', '102 min',
       '93 min', '95 min', '85 min', '83 min', '113 min', '13 min',
       '182 min', '48 min', '145 min', '87 min', '92 min', '80 min',
       '117 min', '128 min', '119 min', '143 min', '114 min', '118 min',
       '108 min', '63 min', '121 min', '142 min', '154 min', '120 min',
       '82 min', '109 min', '101 min', '86 min', '229 min', '76 min',
       '89 min', '156 min', '112 min', '107 min', '129 min', '135 min',
       '136 min', '165 min', '150 min', '133 min', '70 min', '84 min',
       '140 min', '78 min', '2 Seasons', '64 min', '59 min', '139 min',
       '69 min', '148 min', '189 min', '141 min', '130 min', '138 min',
       '81 min', '7 Seasons', '132 min', '123 min', '65 min', '68 min',
       '66 min', '62 min', '74 min', '131 min', '46 min', '38 min',
       '126 min', '39 min', '155 min', '4 Seasons', '159 min', '137 min',
       '12 min', '77 min', '60 min', '49 min', '58 min', '72 min',
       '204 min', '212 min', '25 min', '73 min', '47 min', '71 min',
       '149 min', '15 min', '54 min', '224 min', '162 min', '75 min',
       '79 min', '32 min', '158 min', '164 min', '173 min', '181 min',
       '185 min', '21 min', '6 Seasons', '24 min', '51 min', '151 min',
       '42 min', '22 min', '134 min', '177 min', '52 min', '53 min',
       '8 min', '57 min', '28 min', '50 min', '9 min', '26 min', '45 min',
       '171 min', '27 min', '33 min', '44 min', '29 min', '146 min',
       '20 min', '157 min', '203 min', '41 min', '30 min', '17 min',
       '194 min', '55 min', '5 Seasons', '15 Seasons', '233 min',
       '237 min', '230 min', '195 min', '253 min', '152 min', '190 min',
       '160 min', '208 min', '180 min', '144 min', '5 min', '174 min',
       '170 min', '192 min', '209 min', '187 min', '172 min', '16 min',
       '186 min', '11 min', '8 Seasons', '193 min', '176 min', '56 min',
       '169 min', '40 min', '36 min', '3 min', '168 min', '153 min',
       '35 min', '214 min', '31 min', '163 min', '14 min', '19 min',
       '179 min', '3 Seasons', '43 min', '200 min', '196 min', '167 min',
       '37 min', '178 min', '228 min', '18 min', '205 min', '201 min',
       '191 min'], dtype=object)

Dado que este dato mantiene un patrón "**cantidad `Season(s)`**" o "**minutos `min`**", podemos escribir un patrón que solo nos devuelva los elementos que posean la forma `NUMERO PALABRA`:

In [133]:
df_duration = df_netflix[df_netflix['duration'].str.contains(r'(\d{1,})\s([a-z_A-Z]+)', na=False, regex=True)]
df_duration.shape

C:\Users\Alfonso\AppData\Local\Temp\ipykernel_19948\1987221988.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_duration = df_netflix[df_netflix['duration'].str.contains(r'(\d{1,})\s([a-z_A-Z]+)', na=False, regex=True)]

(6170, 12)

#### **7 - (En caso de no filtrar los datos vacios), `rellenar` los datos vacios**

In [22]:
df_netflix.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

Rellenamos solo las columnas con datos nulos:

In [32]:
valores = {"director": 'No director', "cast": 'No cast', "country": 'No country', 
           "date_added": 'No date', "rating":'No rating', "duration":'No duration'}
df_netflix.fillna(value=valores, inplace=True)

In [33]:
df_netflix.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64